baseURL = "https://bakkesmodwiki.github.io/"
title = "BakkesMod Programming Wiki"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
    geekdocRepo = "https://github.com/BakkesModWiki/BakkesModWiki.github.io"
    geekdocEditPath = "blob/main/content"
    geekdocSearch = true
    geekdocSearchShowParent = true
    geekdocBackToTop = true