baseURL = "http://localhost"
title = "BakkesMod Programming Wiki"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

geekdocRepo = "https://github.com/SimpleAOB/BakkesModWiki-Hugo"
geekdocEditPath = "edit/master/content"
geekdocSearch = true
geekdocSearchShowParent = true
geekdocBackToTop = true