baseURL = "https://bakkesmod-programming-wiki.netlify.app"
title = "BakkesMod Programming Wiki"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
    geekdocRepo = "https://github.com/SimpleAOB/BakkesModWiki-Hugo"
    geekdocEditPath = "blob/master/content"
    geekdocSearch = true
    geekdocSearchShowParent = true
    geekdocBackToTop = true
    relativeURLs = true